config/routes.rb
Rails.application.routes.draw do

root to: 'pages#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

resources :users, only: [:show, :edit, :update] do
  resources :collections, only: [:index, :show, :new, :create]
  resources :savedplaces, only: [:index, :show, :edit, :update] do
    resources :userpics, only: [:create]
    resources :usertips, only: [:update]
  end
end

resources :collectedplaces, only: [:new, :create]

  resources :usertips, only: [:create]

  resources :places, only: [:index, :new, :show, :create, :update, :destroy] do
    get "add", to: "places#add", as: "add", on: :collection
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :collectedplaces
  has_many :savedplaces, through: :collectedplaces
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :find_user, only: [:new, :create, :index, :show]

  def index
    @collections = @user.collections
    @collection = Collection.new
  end

  def new
    @collection = Collection.new
  end

  def show
    @collection = @user.collections.find(params[:id])
    @collectedplaces = @collection.collectedplaces
    @savedplaces = @user.savedplaces

    # DYNAMICALLY build the markers for the view.
    @markers = Gmaps4rails.build_markers(@collectedplaces) do |collected, marker|
      marker.lat collected.savedplace.place.latitude
      marker.lng collected.savedplace.place.longitude
    end
  end

  def create
    @collection = Collection.new(collection_params)
    @collection = current_user.collections.build(collection_params)
    if @collection.save
      flash[:notice] = "Your collection was created."
      redirect_to user_collections_path(current_user)
    else
      flash[:notice] = "Oops something went wrong"
      render :new
    end
  end


private

def collection_params
    params.require(:collection).permit(:name)
  end

  def find_user
    @user = User.find(params[:user_id])
  end


end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/create.html.erb
<h1>Collections#create</h1>
<p>Find me in app/views/collections/create.html.erb</p>

app/views/collections/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-md-offset-3">
       <div class="row text-center">
        <%= link_to image_tag("#{@user.picture}", class: "avatar-large"), root_path %>
       <h1>Placelists</h1>
       <%= form_for [@user, @collection], :html => {class: 'form-inline'} do |f| %>
        <%= f.text_field :name, placeholder: "E.g: Best brunch places in Barcelona", class: "searchplace" %>
        <%= button_tag(type: "submit", class: "btn btn-primary btn-xl") do %><i class="fa fa-plus"></i>
         <% end %>
      <% end %>
      </div>
      <br>
      <br>

      <div class="row">
        <% @collections.reverse.each do |collection| %>
        <div class="panel panel-default ">
          <div class="panel-body">
            <div class="list-group">
              <div class="list-group-item">
                <div class="row-action-primary">
                  <i class="material-icons">view_list</i>
                </div>
                <div class="row-content">
                  <div class="action-secondary"><i class="material-icons">share</i></div>
                  <h5 class="list-group-item-heading"><%= link_to collection.name, user_collection_path(@user,collection) %></h5>

                  <p class="list-group-item-text"> <%= @user.collectedplaces.where(collection: collection).size%> <%="place".pluralize(@user.collectedplaces.where(collection: collection).size) %></p>
                </div>
              </div>
              <div class="list-group-separator"></div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      </div>
  </div>
</div>

 <%#= link_to collection.name, user_collection_path(@user,collection) %>

app/views/collections/new.html.erb
<div class="container">
  <div class="col-lg-6 col-md-offset-3">
    <div class="row">
      <h1>Collections#new</h1>
    </div>


    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body">
        <%= render 'shared/createcollection' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/collections/show.html.erb
<div class="container">
  <div class="col-lg-6 col-md-offset-3">
    <div class="row text-center">

    <%= link_to image_tag("#{@user.picture}", class: "avatar-large"), root_path %>
      <h1><%= @collection.name %></h1>
      <%= form_tag(new_place_path,  method: :get, class: 'form-inline') do |f| %>
        <%= text_field_tag :place, '',class: 'searchplace', id:'pac-input', placeholder: 'Add a new place' %>
          <%= hidden_field_tag :place_id, "", class: "place_id_value" %>
          <%= hidden_field_tag :collection_id, @collection.id %>
          <%= button_tag(type: "submit", class: "btn btn-primary btn-xl") do %><i class="fa fa-plus"></i>
          <% end %>
      <% end %>
      </div>
        <div class="row">

        <div id="btn-toggle-map" class="btn icon-xs">
          <i class="fa fa-map-o"></i> View map</div>

        <div id="btn-toggle-map" class="btn icon-xs">
          <i class="fa fa-book"></i> Order print</div>

    </div>



<!-- list-user-places -->
    <div class="row">
      <div id="list-wrapper">
      <%  @collectedplaces.reverse.each do |collected| %>
        <div class="panel panel-default ">
          <div class="panel-body horizontal">
            <div class="col-xs-3 pull-left">
              <% if collected.savedplace.place.photos.nil? || collected.savedplace.place.photos.empty? %><p>No picture yet</p>
              <% else %>
                 <div class="img-thumb" style="background-image: url(<%= image_url collected.savedplace.place.photos[0].fetch_url(1500), class: "img-responsive" %>);"></div>
              <% end %>
            </div>
            <div class="col-xs-9 pull-right">
              <h5><%= collected.savedplace.place.name %></h5>
              <p><%= collected.savedplace.place.address %></p>

              <p class="text-right"><%= link_to 'Go', user_savedplace_path(@user, collected.savedplace), class: "btn btn-primary btn-xs"%></p>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>

    <div class="row">
      <div id="map" style="width: 100%; height: 600px;"></div>
    </div>

  </div>
</div>




<!-- Maps script with toggle -->

<% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).on('ready', function() {

            var mapOptions = { scrollwheel: false };

              $("#map").addClass("hide");

              $("#btn-toggle-map").on("click", function(){

                $("#map").toggleClass("hide")
                $("#list-wrapper").toggleClass("hide")

                handler = Gmaps.build('Google');
                handler.buildMap({
                  provider: mapOptions,
                  internal: { id: 'map' } }, function(){
                  markers = handler.addMarkers(<%= raw @markers.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                });

              })

            })
          <% end %>
        <% end %>