config/routes.rb
Rails.application.routes.draw do

root to: 'pages#home'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

resources :users, only: [:show, :edit, :update] do
  resources :collections, only: [:index, :show, :new, :create]
  resources :savedplaces, only: [:index, :show, :edit, :update] do
    resources :userpics, only: [:create]
    resources :usertips, only: [:update]
  end
end

resources :collectedplaces, only: [:new, :create]

  resources :usertips, only: [:create]

  resources :places, only: [:index, :new, :show, :create, :update, :destroy] do
    get "add", to: "places#add", as: "add", on: :collection
  end

end

app/models/collectedplace.rb
class Collectedplace < ActiveRecord::Base
  belongs_to :savedplace
  belongs_to :collection
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  has_many :collectedplaces
  has_many :savedplaces, through: :collectedplaces
end

app/models/googlepic.rb
class Googlepic < ActiveRecord::Base
  belongs_to :place
end

app/models/model.rb
class Model < ActiveRecord::Base
  belongs_to :user
end

app/models/place.rb
class Place < ActiveRecord::Base
  serialize :categories, Array
  serialize :photos, Array

  has_many :savedplaces
end

app/models/savedplace.rb
class Savedplace < ActiveRecord::Base
  belongs_to :user
  belongs_to :place
  has_many :usertips
  has_many :userpics
  has_many :collectedplaces
  has_many :collections, through: :collectedplaces
  has_many :user_places_categories
  has_many :usertags

  after_create :map_categories_to_category

  CATEGORIES = ['Food & Drinks', 'Sightseeing', 'Shopping', 'Transport', 'Entertainment', 'Art & Culture', 'Sports', 'Nightlife', 'Relaxation']

  MAPPED_CATEGORIES = {
    'amusement_park' => 'Entertainment',
    'aquarium' => 'Entertainment',
    'art_gallery' => 'Art & Culture',
    'bakery' => 'Food & Drinks',
    'bar' => 'Food & Drinks',
    'bicycle_store' => 'Shopping',
    'book_store' => 'Shopping',
    'bowling_alley' => 'Entertainment',
    'bus_station' => 'Transport',
    'cafe' => 'Food & Drinks',
    'car_rental' => 'Transport',
    'casino' => 'Entertainment',
    'cemetery' => 'Sightseeing',
    'church' => 'Sightseeing',
    'city_hall' => 'Sightseeing',
    'clothing_store' => 'Shopping',
    'convenience_store' => 'Shopping',
    'department_store' => 'Shopping',
    'electronics_store' => 'Shopping',
    'florist' => 'Shopping',
    'food' => 'Food & Drinks',
    'furniture_store' => 'Shopping',
    'grocery_or_supermarket'  => 'Shopping',
    'gym' => 'Sports',
    'hardware_store' => 'Shopping',
    'hindu_temple' => 'Sightseeing',
    'home_goods_store' => 'Shopping',
    'jewelry_store' => 'Shopping',
    'library' => 'Art & Culture',
    'liquor_store' => 'Shopping',
    'meal_delivery' => 'Food & Drinks',
    'meal_takeaway' => 'Food & Drinks',
    'mosque' => 'Sightseeing',
    'movie_theater' => 'Entertainment',
    'museum' => 'Art & Culture',
    'night_club' => 'Nightlife',
    'park' => 'Sightseeing',
    'pet_store' => 'Shopping',
    'pharmacy' => 'Shopping',
    'place_of_worship' => 'Sightseeing',
    'restaurant' => 'Food & Drinks',
    'shoe_store' => 'Shopping',
    'shopping_mall' => 'Shopping',
    'spa' => 'Relaxation',
    'stadium' => 'Sport',
    'store' => 'Shopping',
    'subway_station' => 'Transport',
    'synagogue' => 'Sightseeing',
    'taxi_stand'  => 'Transport',
    'train_station' => 'Transport',
    'zoo' => 'Sightseeing',
    'natural_feature' => 'Sightseeing',
    'point_of_interest' => 'Sightseeing',
    'transit_station'  => 'Transport'
  }

  def map_categories_to_category
    self.place.categories.each do |category|
      if MAPPED_CATEGORIES[category]
        mapped_category = MAPPED_CATEGORIES[category]
        self.user_places_categories.create(savedplace: self, name: mapped_category)
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :savedplaces
  has_many :collections
  has_many :collectedplaces, through: :collections
  has_many :places, through: :savedplaces
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/models/user_places_category.rb
class UserPlacesCategory < ActiveRecord::Base
  belongs_to :savedplace
  validates :name, presence: true, uniqueness: { scope: :savedplace }
end

app/models/userpic.rb
class Userpic < ActiveRecord::Base
  belongs_to :savedplace
  has_attached_file :image, styles: { large: "500x500>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/usertag.rb
class Usertag < ActiveRecord::Base
  belongs_to :savedplace
  validates :tag, presence: true, uniqueness: { scope: :savedplace }
end

app/models/usertip.rb
class Usertip < ActiveRecord::Base
  belongs_to :savedplace
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # before_action :authenticate_user!, only: [:home]

  def home
    @resource = User.new
    @collection = Collection.new
    if user_signed_in?
      @array_cities = current_user.places.pluck("DISTINCT city").reject(&:blank?)
      @user = current_user
      @savedplaces = @user.savedplaces
      @collections = @user.collections
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def devise_mapping
    Devise.mappings[:user]
  end

  def resource_name
    devise_mapping.name
  end

  def resource_class
    devise_mapping.to
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/places_helper.rb
module PlacesHelper


  # def find_photos
  #   if (self.photos.nil? || self.photos.empty?)
  #     content_tag("p") { content_tag(self.photos.count ) }
  #   else
  #     # url_to_image(type: :image).merge!(options(fetch_url(1500), class: "img-responsive"))
  #     link_to image_tag(self.photos[0].fetch_url(1500), class: 'img-responsive')
  #   end
  # end

end

app/helpers/savedplaces_helper.rb
module SavedplacesHelper
end

app/helpers/userpics_helper.rb
module UserpicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/usertips_helper.rb
module UsertipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favspot</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
   <!--  <div class="wrapper"> -->
    <div class="banner"><!-- </div> -->
      <div class="img-gradient"></div>
        <%= render 'shared/navbar' %>
        <%= render 'shared/flashes' %>
        <%= yield %>
      </div>




    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?sensor=false&key=AIzaSyCmtjCERax6MXKjxLv41v76Ai0ooP3cFv0&libraries=places" %>


    <%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

     <%= javascript_include_tag 'application' %>

    <%= yield(:after_js) %>


  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <% if !user_signed_in? %>
    <div class="col-md-8 col-left-home">
      <div class="headline-home">
        <span class="strong">Discover, create and share</span><br>
        <span class="large">YOUR PERSONAL CITY GUIDES</span><br>
        <button class="btn btn-info">take the tour</button>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="col-md-12">
            <h2>Start it here</h2>
            <%= render "devise/shared/linkfacebook" %>
            <hr>
            <%= simple_form_for(@resource, as: resource_name, url: session_path(resource_name)) do |f| %>

              <div class="form-inputs">

                <%= f.input :email, required: false, autofocus: true %>
                <%= f.input :password, required: false %>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
              </div>

              <div class="form-actions">
                <%= f.button :submit, "Log in", class: "btn btn-primary btn-sm" %>
              </div>
            <% end %>

            <%= render "devise/shared/links" %>
          </div>
        </div>
      </div>
    </div>
  </div>
    <% else %>
    <div class="col-md-6 col-md-offset-3">
      <div class="row">
        <%= render "shared/formadd" %>

      </div>


       <!-- Cities list -->
      <div class="row">
        <% @array_cities.each do |city| %>
          <div class="panel panel-default ">
            <div class="panel-body">
              <div class="list-group">
                <div class="list-group-item">
                  <div class="row-picture">
                    <%= image_tag("#{city}.jpg", class: "circle") %>
                  </div>
                  <div class="row-content">
                    <div class="action-secondary"><i class="material-icons">share</i></div>
                    <h5 class="list-group-item-heading"><%=  link_to "#{city}", user_savedplaces_path(@user, :city => "#{city}") %></h5>

                    <p class="list-group-item-text"><%= @user.savedplaces.joins(:place).where("places.city = ?", city).size %> Saved places</p>
                  </div>
                </div>
                <div class="list-group-separator"></div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/shared/_Bootsnippuploadpicture.html.erb
<%= form_for [@user, @savedplace, @userpic], html: {multipart: true, class: "formflat"} do |f| %>

<div class="row">
        <div class="col-xs-12 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
            <!-- image-preview-filename input [CUT FROM HERE]-->
            <div class="input-group image-preview">
                <input type="text" class="form-control image-preview-filename" disabled="disabled"> <!-- don't give a name === doesn't send on POST/GET -->
                <span class="input-group-btn">
                    <!-- image-preview-clear button -->
                    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                        <span class="glyphicon glyphicon-remove"></span> Clear
                    </button>
                    <!-- image-preview-input -->
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span class="image-preview-input-title">Browse</span>
                        <input type="file" accept="image/png, image/jpeg, image/gif" name="input-file-preview"/> <!-- rename it -->
                    </div>
                </span>
            </div><!-- /input-group image-preview [TO HERE]-->
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 select">
          <div class="form-group text-right">
            <%= f.submit "Save", class: "btn btn-primary btn-xs" %>
          </div>
        </div>
      </div>
<% end %>

app/views/shared/_addtocollection.html.erb
<%= form_tag(collectedplaces_path,  method: :post, class: 'form-inline add-collection') do |f| %>
  <%= collection_select :collection, :id, current_user.collections.all, :id, :name, {include_blank: false }, {size: 10, :multiple => true, class: "form-control"} %>
    <%= hidden_field_tag :savedplace_id, "", :value => @savedplace.id %>
    <%= button_tag(type: "submit", class: "btn btn-info btn-xs") do %>Add
    <% end %>
<% end %>

app/views/shared/_createcollection.html.erb
<%= form_for [@user, @collection] do |f| %>

      <div class="col-md-12 select">
        <div class="form-group">
          <label>Collection name</label>
           <%= f.text_field :name, placeholder: "E.g: Best brunch places in Barcelona", class: "form-control" %>
        </div>
      </div>


       <div class="row">
        <div class="col-md-12 select">
          <div class="form-group text-right">
            <%= f.submit "Save", class: "btn btn-info btn-xs" %>
          </div>
        </div>
      </div>
      <% end %>

app/views/shared/_editsavedplace.html.erb
<%= form_for [@user, @savedplace], html: {multipart: true} do |f| %>

      <div class="col-md-12 select">
        <div class="form-group">
          <label>Add tags</label>
           <%= f.text_field :tag, placeholder: "#brunch, #kids, #cool", class: "tokenize" %>
        </div>
      </div>
      <div class="col-md-12 select">
        <div class="form-group">
          <label>Add notes and tips</label>
           <%= f.text_area :tip, rows:3, placeholder: "E.g: Fun atmosphere and great dishes", class: "form-control" %>
        </div>
      </div>

       <div class="row">
        <div class="col-md-12 select">
          <div class="form-group text-right">
            <%= f.submit "Save", class: "btn btn-primary btn-xs" %>
          </div>
        </div>
      </div>
      <% end %>

     <%= content_for :after_js do %>
      <script>$('input.tokenize').tokenfield();</script>
    <% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? -%>
  <div class="container">
    <%= pluralize(object.errors.count, 'error') -%>
    <ul>
      <% object.errors.full_messages.each do |msg| -%>
        <li><%= msg -%></li>
    </ul>
    <% end %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<!-- [FIX:] Why not? I found this little method earlier today -->

<%# unless notice.blank? -%>
  <%#=  notice -%>
<%# unless alert.blank? -%>
  <%#=  alert -%>
<%# end -%>




<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_formadd.html.erb
<div class="panel-tabs">
            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#addplace" aria-controls="addplace" role="tab" data-toggle="tab">Add new place</a></li>
                <li role="presentation"><a href="#addcollection" aria-controls="addcollection" role="tab" data-toggle="tab">Create placelist</a></li>
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="addplace">
               <%= form_tag(new_place_path,  method: :get, class: 'form-inline') do |f| %>
                <%= text_field_tag :place, '',class: 'searchplace', id:'pac-input', placeholder: 'Add a new place' %>
                <%= hidden_field_tag :place_id, "", class: "place_id_value" %>
                <%= button_tag(type: "submit", class: "btn btn-primary btn-xl") do %><i class="fa fa-plus"></i>
                <% end %>
              <% end %>
              <p><%= link_to 'All my places', user_savedplaces_path(@user), class: "btn btn-primary btn-md"%></p>
              </div>
                <div role="tabpanel" class="tab-pane" id="addcollection">
                  <%= form_for [@user, @collection], :html => {class: 'form-inline'} do |f| %>
                <%= f.text_field :name, placeholder: "E.g: Best brunch places in Barcelona", class: "searchplace" %>
                <%= button_tag(type: "submit", class: "btn btn-primary btn-xl") do %><i class="fa fa-plus"></i>
                 <% end %>
              <% end %>
              <p><%= link_to 'All my placelists', user_collections_path(@user), class: "btn btn-primary btn-md"%></p>
            </div>
          </div>
        </div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon fixed">
  <div class="container navbar-wagon-container">

    <a href="">
      <%= image_tag "logo.png", class: "navbar-wagon-logo" %>
    </a>

    <div class="navbar-wagon-pusher"></div>

    <form action="" class="navbar-wagon-search hidden-xs hidden-sm">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/shared/_old_navbar.html.erb
<nav class="navbar-wagon fixed">
  <div class="container navbar-wagon-container">


<%= link_to image_tag("favspot_logo.png", class: "navbar-wagon-logo"), {action: 'home', controller: 'pages'} %>

    <div class="navbar-wagon-pusher"></div>

    <form action="" class="navbar-wagon-search hidden-xs hidden-sm">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>
        <div class="icon-badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="icon-badge icon-badge-blue">3</div>
        </div>
      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/shared/_uploadpicture.html.erb
<%= form_for [@user, @savedplace, @userpic], html: {multipart: true, class: "formflat"} do |f| %>

<div class="row">
  <div class="col-md-12 select">
    <div class="form-group">
      <span class="btn btn-default btn-file">
        <i class="fa fa-cloud-upload fa-lg"></i>Upload Photos
        <%= file_field_tag "image[]", type: :file, multiple: true %>
      </span>
    </div>
  </div>
</div>
<div class="row">
        <div class="col-md-12 select">
          <div class="form-group text-right">
            <%= f.submit "Save", class: "btn btn-primary btn-xs" %>
          </div>
        </div>
      </div>
<% end %>